const status = (options, label = 'Status') => ({
  name: 'status',
  label,
  type: 'select',
  options,
  defaultValue: options[0],
});

function work(path, label, fields, roles, viewOnly) {
  return { path, label, endpointKey: 'items', fields, roles, viewOnly: viewOnly || [] };
}

export const opsRoleHome = {
  reception: '/admissions',
  housekeeping: '/housekeeping',
  porter: '/porter',
  records: '/charts',
  midwife: '/maternity',
  theatre: '/theatre-desk',
  anaesthetist: '/theatre-desk',
  infection: '/infection',
  social: '/social',
  security: '/security',
  catering: '/catering',
  quality: '/quality',
  mortuary: '/mortuary',
};

export const opsPortals = [
  {
    key: 'reception',
    desk: 'reception',
    home: '/admissions',
    roles: ['admin', 'reception'],
    title: 'Reception',
    eyebrow: 'Admissions',
    dashboardTitle: 'Reception dashboard',
    subtitle: 'Register patients and request a floor, ward, and bed. Nursing allocates the bed.',
    extraLinks: [{ to: '/reception', label: 'Patient check-in' }, { to: '/ward-board', label: 'Find a patient' }],
    work: work('/admissions/requests', 'Bed requests', [
      { name: 'patientName', label: 'Patient' },
      { name: 'location', label: 'Requested ward' },
      { name: 'detail', label: 'Reason' },
      status(['WAITING', 'BED_REQUESTED', 'ADMITTED', 'CANCELLED']),
    ], ['admin', 'reception', 'nurse', 'nurse_manager'], ['nurse', 'nurse_manager']),
    users: [{ path: '/admissions/users', role: 'reception', label: 'Users', usersEndpoint: '/admin/reception-users', addEndpoint: '/admin/add-reception' }],
  },
  {
    key: 'housekeeping',
    desk: 'housekeeping',
    home: '/housekeeping',
    roles: ['admin', 'housekeeping'],
    title: 'Housekeeping',
    eyebrow: 'Environmental services',
    dashboardTitle: 'Housekeeping dashboard',
    subtitle: 'Cleaning tasks, and beds that can be released from cleaning back to available.',
    beds: { path: '/housekeeping/beds', label: 'Beds to clean' },
    work: work('/housekeeping/tasks', 'Cleaning tasks', [
      { name: 'patientName', label: 'Area note', required: false },
      { name: 'location', label: 'Location' },
      { name: 'detail', label: 'Task' },
      status(['OPEN', 'IN_PROGRESS', 'DONE']),
    ]),
    users: [{ path: '/housekeeping/users', role: 'housekeeping', label: 'Users', usersEndpoint: '/admin/housekeeping-users', addEndpoint: '/admin/add-housekeeping' }],
  },
  {
    key: 'porter',
    desk: 'porter',
    home: '/porter',
    roles: ['admin', 'porter'],
    title: 'Porters',
    eyebrow: 'Patient transport',
    dashboardTitle: 'Porter dashboard',
    subtitle: 'Move patients to a known floor, ward, and bed.',
    work: work('/porter/jobs', 'Transport jobs', [
      { name: 'patientName', label: 'Patient' },
      { name: 'location', label: 'From' },
      { name: 'detail', label: 'To' },
      status(['REQUESTED', 'IN_TRANSIT', 'DONE']),
    ]),
    users: [{ path: '/porter/users', role: 'porter', label: 'Users', usersEndpoint: '/admin/porter-users', addEndpoint: '/admin/add-porter' }],
  },
  {
    key: 'records',
    desk: 'records',
    home: '/charts',
    roles: ['admin', 'records'],
    title: 'Medical records',
    eyebrow: 'Health records',
    dashboardTitle: 'Medical records dashboard',
    subtitle: 'Pull and file the chart for the ward where the patient is.',
    work: work('/charts/requests', 'Chart requests', [
      { name: 'patientName', label: 'Patient' },
      { name: 'location', label: 'Location' },
      { name: 'detail', label: 'Request' },
      status(['REQUESTED', 'PULLED', 'FILED']),
    ]),
    users: [{ path: '/charts/users', role: 'records', label: 'Users', usersEndpoint: '/admin/records-users', addEndpoint: '/admin/add-records' }],
  },
  {
    key: 'midwife',
    desk: 'midwife',
    home: '/maternity',
    roles: ['admin', 'midwife'],
    title: 'Maternity',
    eyebrow: 'Midwifery',
    dashboardTitle: 'Maternity dashboard',
    subtitle: 'Antenatal, labour, and postnatal care.',
    work: work('/maternity/cases', 'Maternity cases', [
      { name: 'patientName', label: 'Patient' },
      { name: 'location', label: 'Location' },
      { name: 'detail', label: 'Notes' },
      status(['ANTENATAL', 'LABOUR', 'POSTNATAL', 'DISCHARGED']),
    ]),
    users: [{ path: '/maternity/users', role: 'midwife', label: 'Users', usersEndpoint: '/admin/midwife-users', addEndpoint: '/admin/add-midwife' }],
  },
  {
    key: 'theatre',
    desk: 'theatre',
    home: '/theatre-desk',
    roles: ['admin', 'theatre', 'anaesthetist'],
    title: 'Theatre',
    eyebrow: 'Operating theatres',
    dashboardTitle: 'Theatre desk',
    subtitle: 'Theatre nurses and anaesthetists track cases. Utilisation stays on the theatre board.',
    extraLinks: [{ to: '/theatres', label: 'Theatre utilisation' }],
    work: work('/theatre-desk/cases', 'Theatre cases', [
      { name: 'patientName', label: 'Patient' },
      { name: 'location', label: 'Theatre' },
      { name: 'detail', label: 'Procedure' },
      status(['BOOKED', 'IN_THEATRE', 'RECOVERY', 'DONE']),
    ], ['admin', 'theatre', 'anaesthetist']),
    users: [
      { path: '/theatre-desk/users', role: 'theatre', label: 'Theatre nurses', usersEndpoint: '/admin/theatre-users', addEndpoint: '/admin/add-theatre' },
      { path: '/theatre-desk/anaesthetists', role: 'anaesthetist', label: 'Anaesthetists', usersEndpoint: '/admin/anaesthetist-users', addEndpoint: '/admin/add-anaesthetist' },
    ],
  },
  {
    key: 'infection',
    desk: 'infection',
    home: '/infection',
    roles: ['admin', 'infection'],
    title: 'Infection prevention',
    eyebrow: 'IPC',
    dashboardTitle: 'Infection prevention dashboard',
    subtitle: 'Isolation and precaution cases linked to a ward bed.',
    work: work('/infection/cases', 'Isolation cases', [
      { name: 'patientName', label: 'Patient' },
      { name: 'location', label: 'Bed location' },
      { name: 'detail', label: 'Precaution' },
      status(['SUSPECTED', 'CONFIRMED', 'CLEARED']),
    ]),
    users: [{ path: '/infection/users', role: 'infection', label: 'Users', usersEndpoint: '/admin/infection-users', addEndpoint: '/admin/add-infection' }],
  },
  {
    key: 'social',
    desk: 'social',
    home: '/social',
    roles: ['admin', 'social'],
    title: 'Social work',
    eyebrow: 'Social work',
    dashboardTitle: 'Social work dashboard',
    subtitle: 'Social work cases for discharge, family support, and welfare.',
    work: work('/social/cases', 'Social cases', [
      { name: 'patientName', label: 'Patient' },
      { name: 'location', label: 'Location' },
      { name: 'detail', label: 'Need' },
      status(['OPEN', 'ACTIVE', 'CLOSED']),
    ]),
    users: [{ path: '/social/users', role: 'social', label: 'Users', usersEndpoint: '/admin/social-users', addEndpoint: '/admin/add-social' }],
  },
  {
    key: 'security',
    desk: 'security',
    home: '/security',
    roles: ['admin', 'security'],
    title: 'Security',
    eyebrow: 'Hospital security',
    dashboardTitle: 'Security dashboard',
    subtitle: 'Access and incident records for the hospital.',
    work: work('/security/incidents', 'Incidents', [
      { name: 'patientName', label: 'Reported by', required: false },
      { name: 'location', label: 'Location' },
      { name: 'detail', label: 'Summary' },
      status(['OPEN', 'CLOSED']),
    ]),
    users: [{ path: '/security/users', role: 'security', label: 'Users', usersEndpoint: '/admin/security-users', addEndpoint: '/admin/add-security' }],
  },
  {
    key: 'catering',
    desk: 'catering',
    home: '/catering',
    roles: ['admin', 'catering'],
    title: 'Catering',
    eyebrow: 'Patient meals',
    dashboardTitle: 'Catering dashboard',
    subtitle: 'Ward diet and meal orders.',
    work: work('/catering/orders', 'Meal orders', [
      { name: 'patientName', label: 'Patient', required: false },
      { name: 'location', label: 'Ward' },
      { name: 'detail', label: 'Diet' },
      status(['ORDERED', 'SERVED', 'CANCELLED']),
    ]),
    users: [{ path: '/catering/users', role: 'catering', label: 'Users', usersEndpoint: '/admin/catering-users', addEndpoint: '/admin/add-catering' }],
  },
  {
    key: 'quality',
    desk: 'quality',
    home: '/quality',
    roles: ['admin', 'quality'],
    title: 'Quality',
    eyebrow: 'Complaints and quality',
    dashboardTitle: 'Quality dashboard',
    subtitle: 'Complaint acknowledgement within 5 days and resolution within 25 days.',
    extraLinks: [{ to: '/complaints', label: 'Complaints desk' }],
    users: [{ path: '/quality/users', role: 'quality', label: 'Users', usersEndpoint: '/admin/quality-users', addEndpoint: '/admin/add-quality' }],
  },
  {
    key: 'mortuary',
    desk: 'mortuary',
    home: '/mortuary',
    roles: ['admin', 'mortuary'],
    title: 'Mortuary',
    eyebrow: 'Mortuary',
    dashboardTitle: 'Mortuary dashboard',
    subtitle: 'Register of deceased patients received and released.',
    work: work('/mortuary/register', 'Deceased register', [
      { name: 'patientName', label: 'Deceased' },
      { name: 'location', label: 'From ward' },
      { name: 'detail', label: 'Notes' },
      status(['RECEIVED', 'RELEASED']),
    ]),
    users: [{ path: '/mortuary/users', role: 'mortuary', label: 'Users', usersEndpoint: '/admin/mortuary-users', addEndpoint: '/admin/add-mortuary' }],
  },
];
